## This file defines common functions used for data processing.
load_metrics_file <- function(benchmark_name, iter, data_set) {
  filename <- paste0("/../Data/Metrics/", benchmark_name, "-", iter, "/", data_set, ".csv")
  read.table(filename, sep="\t", header=TRUE, fill=TRUE, comment.char = "")
}

load_data_file <- function (file, row_names) {
  if (missing(row_names)) {
    # these row names are hard coded and might not be applicable
    # names like this are generated by ReBench
    row_names <- c("TimeStamp", "Value", "Unit", "Criterion", "Benchmark",
                   "VM", "Suite", "Extra", "Warmup", "Cores", "InputSize",
                   "Var")
  }
  
  bench <- read.table(file, sep="\t", header=FALSE, col.names=row_names, fill=TRUE)
  bench$rid = seq_len(nrow(bench))
  bench <- ddply(bench, ~ Benchmark + VM + Var + Extra + Cores + Suite, transform,
                 Iteration = rid - min(rid))
  
  bench
}

getAndPrepareData <- function(filename, filterColumns) {
  data <- load_data_file(filename)
  if (!missing(filterColumns)) {
    data <- subset(data, select=filterColumns)
  }
  data
}

change_names <- function(data, name_map, column) {
  levels(data[,column])  <- map_names(
    levels(data[,column]),
    name_map)
  data
}

map_names <- function(old_names, name_map) {
  for (i in 1:length(old_names)) {
    old_name <- old_names[[i]]
    if (old_name %in% names(name_map)) {
      old_names[i] <- name_map[[old_name]]
    }
  }
  old_names
}

vmNamesMap <- function() {
  name_map <-     list("Java8U66"              = "Java, 1.8.0_66",
                       #                       "JRubyJ8"               = "Ruby, JRuby 9.0.4.0 + indy", #invokedynamic
                       #                       "MRI22"                 = "Ruby, MRI 2.2",
                       #                       "MRI23"                 = "Ruby, MRI 2.3",
                       #                       "RBX314"                = "Ruby, Rubinius 3.14",
                       #                       "GraalJS"               = "JavaScript, GraalJS",
                                               "Node"                  = "Node.js",
                       #                       "SOMns"                 = "SOMns, Newspeak, master",
                       #                       "SOMns-Enterprise"      = "SOMns, Newspeak",
                       #                       "JRubyTruffle"          = "Ruby, JRuby+Truffle, truffle head (basic)",
                       #                       "JRubyTruffleEnterprise" = "Ruby, JRuby+Truffle", # , truffle head
                       
                       "TruffleSOM-graal"  = "SOMpe",
                       "TruffleMate-graal" = "MATEpe",
                       "RTruffleSOM"       = "SOMmt",
                       "RTruffleMate"      = "MATEmt",
                       "RTruffleMate-envInObj"      = "MATEmt-envInObj",
                       "TruffleSOM-graal-enterprise"  = "SOMpe-Ent",
                       "TruffleMate-graal-enterprise" = "MATEpe-Ent",
                       "TruffleMate-graal-enterprise-envInObj" = "MATEpe-Ent-envInObj",
                       "Pharo"                  = "Pharo")
  #                       "TruffleSOM-graal-no-split" = "TruffleSOM.ns",
  #                       "SOMpp"                 = "SOM++")
  # Rename
  name_map
}

getFilteredData <- function(filename, filterColumns, vmNames, iterationsFilename, iterationsColNames, numberOfIterations) {
  data <- getAndPrepareData(filename, filterColumns)
  data <- change_names(data, vmNames, "VM")
  steady <- selectIterationsAndInlining(data, iterationsFilename, iterationsColNames, numberOfIterations)
  steady
}

getWarmedupData <- function(filename, filterColumns, vmNames, numberOfIterations) {
  data <- getAndPrepareData(filename, filterColumns)
  data <- change_names(data, vmNames, "VM")
  steady <- selectWarmedupData(data, numberOfIterations)
  steady
}

microBenchmarks <- c("Bounce", "List", "Mandelbrot", "NBody", "Permute", "Queens", "Sieve", "Storage", "Towers")
macroBenchmarks <- c("CD", "DeltaBlue", "Havlak", "Json", "Richards")

mtVMs <- c("SOMmt", "MATEmt", "MATEmt-envInObj")
peVMs <- c("SOMpe", "SOMpe-Ent", "MATEpe", "MATEpe-Ent", "MATEpe-Ent-envInObj")